### ISSUE TITLE
Intermittent segmentation faults

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#25]
Over several runs, it appears there's an intermittent segmentation fault 

```
~/git/c/gtklock master
🖳  ./gtklock 

** (gtklock:41453): WARNING **: 16:30:43.099: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

~/git/c/gtklock master
🖳  ./gtklock

** (gtklock:41633): WARNING **: 16:30:52.752: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
zsh: segmentation fault (core dumped)  ./gtklock

~/git/c/gtklock master 7s
🖳  ./gtklock

** (gtklock:41802): WARNING **: 16:31:03.687: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

~/git/c/gtklock master
🖳  ./gtklock

** (gtklock:41950): WARNING **: 16:31:12.051: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
```

backtrace:

```
gdb) backtrace
#0  0x000000000040558b in auth_pw_check ()
#1  0x000000000040834e in window_pw_wait ()
#2  0x00007efc51250302 in g_thread_proxy (data=0x8b82a0) at ../glib/gthread.c:827
#3  0x00007efc5105be2d in start_thread (arg=<optimized out>) at pthread_create.c:442
#4  0x00007efc510e11b0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by jovanlanik** [comment]
Any specific way to replicate? Do you attempt to unlock or put in a wrong password? Also what version of gtklock?

**Comment by ldelossa** [comment]
Hey, sorry for delay. 

I have been testing mostly with fingerprint, so I suppose it could be something with fprintd as well. 

I can no longer reproduce this with latest HEAD, so closing.
